# DISPLAY
WIDTH = 1200
HALF_WIDTH = WIDTH // 2
HEIGHT = 600

# FONTS
SMALL_FONT = "Monaco 20"
REGULAR_FONT = "Monaco 30"
HEADING_FONT = "Monaco 90"
EXTRA_FONT = "Monarco 120"

# PLACES
INTRO_SELECT_START = (120, 300)
INTRO_SELECT_OFFSET = 50
INTRO_COMPONENT_OFFSET = 250
INTRO_COMPONENT_WIDTH = 700

SELECT_ACTIVE = '-> '
SELECT_ACTIVE_OFFSET = 70

# ACTIONS
EXIT_INTRO = 'Exit Intro'
EXIT_GAME = 'Exit Game'
EXIT_MENU = 'Exit Menu'
EXIT_LEVEL_MENU = 'Exit Level Menu'
EDIT_NAME = 'Edit Name'
START_HANGMAN = 'Start Hangman'
START_CRACK_THE_CODE = 'Start Crack the Code'

# FILES
USER_FILE = 'data/user.txt'
USER_NAME = 'name'
USER_SCORE = 'score'