# FONTS
SMALL_FONT = "Menlo 20"
REGULAR_FONT = "Menlo 30"
HEADING_FONT = "Menlo 90"

# PLACES
INTRO_SELECT_START = (120, 300)
INTRO_SELECT_OFFSET = 50

SELECT_ACTIVE = '-> '
SELECT_ACTIVE_OFFSET = 70
