# DISPLAY
WIDTH = 1200
HALF_WIDTH = WIDTH // 2
HEIGHT = 600

# FONTS
SMALL_FONT = "Monaco 20"
REGULAR_FONT = "Monaco 30"
HEADING_FONT = "Monaco 90"

# PLACES
INTRO_SELECT_START = (120, 300)
INTRO_SELECT_OFFSET = 50
INTRO_COMPONENT_OFFSET = 250
INTRO_COMPONENT_WIDTH = 700

SELECT_ACTIVE = '-> '
SELECT_ACTIVE_OFFSET = 70
